In [6]:
# 1) Vector, Indexing and Arithmetic
# a) Create a variable "a", that has a sequence of numbers,
# ranging from 4 and to 50 with an increment of 4.
import numpy as np
a= np.arange(4,50,4)
a

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [7]:
# b) what is the sum of the 5th and 10th element
# in "a"
a[4] + a[9]

60

In [8]:
# c) Except the 5th element, print all other
# elements in the above vector "a".
np.delete(a,4)

array([ 4,  8, 12, 16, 24, 28, 32, 36, 40, 44, 48])

In [11]:
# d) Except the 3rd and 5th element, print all
# other elements in the above vector "a"
np.delete(a,[2,4,5,6,7])

array([ 4,  8, 16, 36, 40, 44, 48])

In [ ]:
# adfdf
# gddh
# fhfh