##### 1) Find the 2nd largest number from any given set of random numbers:

In [1]:
import numpy as np
numb = np.random.randint(1,100, 15)
numb

array([46, 63, 71, 37, 71, 62, 58, 17, 65, 68,  2, 74, 57, 47, 32])

In [2]:
numb = -np.sort(-numb)
numb

array([74, 71, 71, 68, 65, 63, 62, 58, 57, 47, 46, 37, 32, 17,  2])

In [3]:
numb[1]

71

##### 2) Find 2nd and 4th largest numbers from any given set of random numbers:

In [7]:
numb[[1,3]]

array([71, 68])

#### 3) Create a function to allow user to select an array of large numbers from any given set of random numbers

In [8]:
numb = np.random.randint(1,100,15)
numb

array([74,  6, 68, 49, 33, 45, 59, 99, 77, 56, 57, 61, 38, 24, 86])

In [9]:
def userDef(arr):
    sortN = -np.sort(-numb)
    return sortN[arr]

In [10]:
userDef([1,3])

array([86, 74])

In [11]:
userDef(0)

99

In [12]:
userDef(14)

6

In [14]:
userDef([0,1,14])

array([99, 86,  6])

In [15]:
a = np.random.randint(1,100,25)
a

array([54, 12, 91, 14, 81, 98, 69, 66, 82, 43, 43, 90, 49, 51, 55, 39,  7,
       50, 38, 60,  7, 86, 91, 30, 47])

In [16]:
-np.sort(-a)

array([98, 91, 91, 90, 86, 82, 81, 69, 66, 60, 55, 54, 51, 50, 49, 47, 43,
       43, 39, 38, 30, 14, 12,  7,  7])

In [17]:
a

array([54, 12, 91, 14, 81, 98, 69, 66, 82, 43, 43, 90, 49, 51, 55, 39,  7,
       50, 38, 60,  7, 86, 91, 30, 47])