In [1]:
import numpy as np

In [2]:
a = np.array([2,56,78,42])
a

array([ 2, 56, 78, 42])

In [3]:
len(a)

4

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.array([4,7,2,8,"hi"])

In [6]:
b

array(['4', '7', '2', '8', 'hi'], dtype='<U11')

In [7]:
type(b)

numpy.ndarray

In [8]:
a[1]

56

In [9]:
a[0]

2

In [11]:
a[len(a)-1]

42

In [14]:
x = np.array([23,56,45,89,4,67,12,44,9,77,22,11])
x

array([23, 56, 45, 89,  4, 67, 12, 44,  9, 77, 22, 11])

In [16]:
x[1:4]

array([56, 45, 89])

In [17]:
x[-1]

11

In [18]:
x[-2]

22

In [20]:
x[-3:-1]

array([77, 22])