In [1]:
# a) Generate 20 Random numbers that are either between 
# 1 and 40 or between 70 and 100
import numpy as np
l1 = np.arange(1,41)
l2 = np.arange(70,101)

In [5]:
l3 = np.append(l1,l2)
b = np.random.choice(l3, 20)

In [6]:
print(b)

[ 71  74  21  85  72  86  77  91  72  32   8  90   7  83  20  78  33  97
 100   4]


In [8]:
# b) Find the largest number in the above array and what
# is the index of that number ?
print(np.max(b))
print(np.argmax(b))

100
18


In [11]:
# c) How many numbers are between 20 and 40 ?
d = b[(b>=20) & (b<=40)]
print(d)
len(d)

[21 32 20 33]


4

In [13]:
# d) What is the index of the number(s) less than 20 ?
np.argwhere(b<20)

array([[10],
       [12],
       [19]], dtype=int64)

In [14]:
b

array([ 71,  74,  21,  85,  72,  86,  77,  91,  72,  32,   8,  90,   7,
        83,  20,  78,  33,  97, 100,   4])

In [16]:
# e) Rank all the numbers in descending order?
# Note: This was not covered in the tutorial.
# Please explore and see if you are able to get 
# a solution.
incr = np.sort(b)
np.flip(incr)

array([100,  97,  91,  90,  86,  85,  83,  78,  77,  74,  72,  72,  71,
        33,  32,  21,  20,   8,   7,   4])