In [1]:
import numpy as np

In [13]:
a = np.random.randint(1,100,10)
a

array([55, 46, 27, 67,  4, 31, 22, 24, 33, 52])

In [14]:
a[a>60]

array([67])

In [18]:
a[(a> 50) | (a<10)]

array([55, 67,  4, 52])

In [19]:
sum(a)

361

In [20]:
a.sum()

361

In [21]:
np.sum(a)

361

In [22]:
np.prod(a)

2110170624

In [23]:
np.argmax(a)

3

In [24]:
a

array([55, 46, 27, 67,  4, 31, 22, 24, 33, 52])

In [25]:
np.argmin(a)

4

In [26]:
np.min(a)

4

In [27]:
np.max(a)

67